debugging secrets.properties not being created

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -27,12 +27,29 @@ jobs:
     needs: build
     runs-on: ubuntu-latest
     steps:
+      - name: Verify file exists
+        run: |
+          if [ -f "$GITHUB_WORKSPACE/secrets.properties" ]; then
+            echo "File found successfully!"
+          else
+            echo "File not found! Searching directory..."
+            ls -R $GITHUB_WORKSPACE
+          fi
+      - name: Debug file location
+        run: |
+          touch secrets.properties
+          echo "Current directory is:"
+          pwd
+          echo "Files in current directory:"
+          ls -F
+          echo "Check if file exists in app/ folder:"
+          ls -F app/ || echo "app/ folder not found or empty"
       - name: Checkout repository
         uses: actions/checkout@v4
       - name: Create secrets file
         run: |
           printf "CIENTID=20302211ABH62HY6" > $GITHUB_WORKSPACE/secrets.properties
-      - name: Set up JDK 11
+      - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
           java-version: '17'
@@ -41,4 +58,4 @@ jobs:
       - name: Grant execute permission for gradlew
         run: chmod +x gradlew
       - name: Run Unit Tests
-        run: ./gradlew test
+        run: ./gradlew test --stacktrace
